### ISSUE TITLE
Encoding issue wit sitemap.xml in Adobe Cloud

### ISSUE THREAD

**Issue by ogebert** [rockwareGmbHCoKG/textvariables#2]
We have an issue with the encoding in a sitemap.xml file. If the package is installed (even with config set to inactive), äöü, ... are broken in the XML. As soon as the package is removed, things are working fine again.

**Comment by monalishah** [comment]
TokenServletFilter -> Here, we have to encode the response with utf-8 for "if (!touched)" condition.

**Comment by edoardo-goracci** [comment]
Implemented suggested fix: https://github.com/rockwareGmbHCoKG/textvariables/pull/3 (thanks @monalishah)

New release: https://github.com/rockwareGmbHCoKG/textvariables/releases/tag/v3.2.3

**Comment by anandsharma04** [comment]
Hi @edoardo-goracci 

This fix is breaking the image rendering.

Ex:-
https://www.<domainname>/content/<project>/mypage/_jcr_content/parcontent_top/carousel/item_1658520065658/image3.img.jpg/1681302721089.jpg

OOTB Adaptive image component in AEM is also using above way of rendering images (using .img selector). None of the images are loading fine.

Can you please validate your fix against OOTB adaptiveImage component.
